#!/bin/sh
# This is file 'vc' from the vc bundle for TeX.
# The original file can be found at CTAN:support/vc.
# This file is Public Domain.

# Parse command line options.
full=0
mod=0
while [ -n "$(echo $1 | grep '-')" ]; do
    case $1 in 
       -f ) full=1 ;;
       -m ) mod=1 ;;
       *  ) echo 'usage: vc [-f] [-m]'
            exit 1
    esac
    shift
done
# English locale.
LC_ALL=C
svn info -R . |gawk -v script=info -v full=$full -f vc-svn.awk > vc.tex
if [ "$mod" = 1 ]
then
  svn status |gawk -v script=status -f vc-svn.awk >> vc.tex
fi
